//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAHASA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FAHASAEntities : DbContext
    {
        public FAHASAEntities()
            : base("name=FAHASAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaoCaoBanHang> BaoCaoBanHangs { get; set; }
        public virtual DbSet<CT_BaoCaoBanHang> CT_BaoCaoBanHang { get; set; }
        public virtual DbSet<CT_PhieuGhiNoDaiLy> CT_PhieuGhiNoDaiLy { get; set; }
        public virtual DbSet<CT_PhieuKiemKho> CT_PhieuKiemKho { get; set; }
        public virtual DbSet<CT_PhieuNhap> CT_PhieuNhap { get; set; }
        public virtual DbSet<CT_PhieuXuat> CT_PhieuXuat { get; set; }
        public virtual DbSet<CT_PhieuYeuCauBan> CT_PhieuYeuCauBan { get; set; }
        public virtual DbSet<CT_PhieuYeuCauMua> CT_PhieuYeuCauMua { get; set; }
        public virtual DbSet<CT_ThongKeChoNXB> CT_ThongKeChoNXB { get; set; }
        public virtual DbSet<DaiLy> DaiLies { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<NhaXuatBan> NhaXuatBans { get; set; }
        public virtual DbSet<PhieuGhiNoDaiLy> PhieuGhiNoDaiLies { get; set; }
        public virtual DbSet<PhieuKiemKho> PhieuKiemKhoes { get; set; }
        public virtual DbSet<PhieuNhap> PhieuNhaps { get; set; }
        public virtual DbSet<PhieuXuat> PhieuXuats { get; set; }
        public virtual DbSet<PhieuYeuCauBan> PhieuYeuCauBans { get; set; }
        public virtual DbSet<PhieuYeuCauMua> PhieuYeuCauMuas { get; set; }
        public virtual DbSet<Sach> Saches { get; set; }
        public virtual DbSet<ThongKeChoNXB> ThongKeChoNXBs { get; set; }
    }
}
