//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySachT
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuXuat
    {
        public PhieuXuat()
        {
            this.CT_PhieuXuat = new HashSet<CT_PhieuXuat>();
        }
    
        public int MaPhieu { get; set; }
        public System.DateTime NgayGio { get; set; }
        public string NguoiNhan { get; set; }
        public Nullable<int> TongTien { get; set; }
        public int MaDaiLy { get; set; }
        public bool TinhTrang { get; set; }
    
        public virtual ICollection<CT_PhieuXuat> CT_PhieuXuat { get; set; }
        public virtual DaiLy DaiLy { get; set; }
    }
}
